apiVersion: v1
kind: Service
metadata:
  name: todo-service
  annotations:
    # https://manual.kinx.net/ixcloud/ixcloud/Container/k8s_LB
    # load balancer annotations
    service.beta.kubernetes.io/kinx-load-balancer-backend-protocol: "http"
    # if backend-protocol == terminated_https
    # service.beta.kubernetes.io/kinx-load-balancer-tls-container-ids: 
    # if backend-protocol == terminated_https
    # service.beta.kubernetes.io/kinx-load-balancer-low-tlsv: "false"
    # if backend-protocol == http
    service.beta.kubernetes.io/kinx-load-balancer-redirect-http: "false"
    # # if backend-protocol == tcp
    # service.beta.kubernetes.io/kinx-load-balancer-proxy-protocol: "false"
    # load balancer monitoring annotations
    service.beta.kubernetes.io/kinx-load-balancer-healthcheck-interval: "5"
    service.beta.kubernetes.io/kinx-load-balancer-healthcheck-retry: "3"
    service.beta.kubernetes.io/kinx-load-balancer-healthcheck-timeout: "5"
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer