name: gitAction cicd test

on:
  push:
    branches:
      - feature/k8s
        
        
jobs:
  build:
    runs-on: self-hosted
    outputs:
      new-image-tag: ${{ env.COMMIT_ID }}
    steps:
    - uses: actions/checkout@v2
    - name: github branch and commit name retrieval
      run: |
        echo ci/cd triggered for :  ${{ github.repository }}
        echo on branch :  ${{ github.ref_name }}
        echo for action :  ${{ github.event_name}}
        echo commit id :  ${{ github.event.head_commit.id}}
        echo commit name :  '${{ github.event.head_commit.message}}'
        echo "COMMIT_ID=$(echo ${{ github.event.head_commit.id}})" >> $GITHUB_ENV
    - name: build docker image and push to local docker registry
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: localhost:5000/test/todo-app:latest, localhost:5000/test/todo-app:${{ env.COMMIT_ID }}
  # deploy:
  #   needs: build
  #   runs-on: self-hosted
  #   steps:
  #   - name: k8s set kubeconfig
  #     uses: Azure/k8s-set-context@v2
  #     with:
  #       method: kubeconfig
  #       kubeconfig: ${{ secrets.KUBECONFG_SECRET }}
  #   # - name: test kubectl
  #   #   run: kubectl get pods -o wide
  #   - name: change deployment image
  #     run: kubectl set image deployment/todo-deployment todo=192.168.21.10:5000/test/todo-app:${{ needs.build.outputs.new-image-tag }}
  #   - name: wait rollout and get deployment
  #     run: sleep 60 && kubectl get deployment -o wide